import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Head from 'next/head'; // Import Head from next/head

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // add suppressHydrationWarning={true} to remove the error in html and body element
    <html lang="en" suppressHydrationWarning={true}> 
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Header />
        {children}
      </body>
    </html>
  );
}
